# Generated by Django 5.2.8 on 2025-12-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_announcementcomment_author_useractivity'),
        ('users', '0008_profilereview_is_edited_profilereview_updated_at_and_more'),
    ]

    operations = [
    ]
