# Generated by Django 5.2.8 on 2026-04-14 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_announcement_video_url_reviewrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRating',
            new_name='GuideReviewRating',
        ),
    ]
