services:
  db:
    image: postgres:14
    container_name: skillissue_db
    environment:
      POSTGRES_DB: skill_issue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: skillissue_frontend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  postgres_data: